" nilognap's vimrc

function! LoadVimLsp()
	Plug 'prabirshrestha/vim-lsp'
	Plug 'mattn/vim-lsp-settings'
	" let g:lsp_settings = {
		" \ "eclipse-jdt-ls": {
		" \	"initialization_options": {
		" \		"settings": {
		" \			"java.completion.filteredTypes": [
		" \				"java.lang.*"
		" \			]
		" \		}
		" \	}
		" \ }
	" \ }
	setlocal omnifunc=lsp#complete
	setlocal signcolumn=yes
	nnoremap <buffer> gd <plug>(lsp-definition)
	nnoremap <buffer> gs <plug>(lsp-document-symbol-search)
endfunction

function! LoadPlugins()
	call plug#begin()

	" call LoadVimLsp()

	call plug#end()
endfunction
" call LoadPlugins()

" function! LoadConfig()
	" runtime config/settings.vim
	" runtime config/ui.vim
	" runtime config/colorscheme.vim
" 
	" runtime config/indent.vim
	" runtime config/search.vim
" 
	" runtime config/helpers.vim
" 
	" runtime config/autocmds.vim
	" runtime config/functions.vim
	" runtime config/utilities.vim
" 
	" runtime config/snippets.vim
	" runtime config/tab.vim
	" runtime autocomplete.vim
" 
	" runtime config/mappings.vim
" endfunction
" call LoadConfig()

runtime! config/*.vim
